export const cpfCodes = [
    { code: 'CON', description: 'Contributions' },
    { code: 'HSE', description: 'HDB flats and other residential properties' },
    { code: 'PMI', description: 'Private Medical Insurance' },
    { code: 'DPS', description: 'Dependants\' Protection Scheme' },
    { code: 'CSL', description: 'CareShield Life' },
    { code: 'ADJ', description: 'Adjustment / Interest on recovered CPF contributions' },
    { code: 'AMP', description: 'Additional Monthly Payout' },
    { code: 'BAL', description: 'Balance' },
    { code: 'CLA', description: 'CPF LIFE Annuity Premium' },
    { code: 'CLB', description: 'CPF LIFE Bonus (L-Bonus)' },
    { code: 'CLC', description: 'CPF LIFE Change of plan' },
    { code: 'CLI', description: 'CPF LIFE Payout' },
    { code: 'CLR', description: 'Refund from CPF LIFE' },
    { code: 'CLS', description: 'CPF LIFE Switch of plan' },
    { code: 'DPC', description: 'Dependants\' Protection Scheme return of premium refund' },
    { code: 'DPR', description: 'Dependants\' Protection Scheme premium refund' },
    { code: 'DPP', description: 'DPS Fund privatisation residual distribution' },
    { code: 'DVB', description: 'Deferment and/or Voluntary Deferment Bonus' },
    { code: 'EDN', description: 'Education Scheme' },
    { code: 'ESH', description: 'ElderShield' },
    { code: 'HPR', description: 'Home Protection Scheme Rebate' },
    { code: 'HPS', description: 'Home Protection Scheme' },
    { code: 'HRF', description: 'Withdrawal from balance of housing refund' },
    { code: 'INT', description: 'Interest for the whole year' },
    { code: 'INV', description: 'CPF Investment Scheme' },
    { code: 'MED', description: 'Medisave' },
    { code: 'MSH', description: 'MediShield' },
    { code: 'MSL', description: 'MediShield Life' },
    { code: 'MGS', description: 'Medical Grounds Scheme' },
    { code: 'PTY', description: 'Non-residential property' },
    { code: 'RFD', description: 'Refund of overpaid contributions' },
    { code: 'RSS', description: 'Retirement Sum Scheme' },
    { code: 'RST', description: 'Top-ups under CPF Retirement Sum Topping-Up Scheme' },
    { code: 'SNS', description: 'Special Needs Savings Scheme' },
    { code: 'SE:', description:'Payment by self-employed person' },
    { code: 'TFR', description: 'Transfer between accounts' },
    { code: 'WDL', description: 'Withdrawal of CPF savings' },
];
