# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Sledger Web CI
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: self-hosted
    steps:
    - uses: actions/checkout@v2
    - uses: actions/cache@v1
      with:
        path: node_modules
        key: node_modules-${{ hashFiles('**/package-lock.json') }}
        restore-keys: |
          node_modules-
    - name: npm install
      run: npm install
    - name: Set environment file
      run: printf "BROWSER=NONE\nREACT_APP_BASE_URL=${{ SECRETS.BASE_URL }}" > .env
    - name: npm build
      run: npm run build
    - name: Derive tag from package.json version
      run: |
        export PACKAGE_VERSION=`sed -n 's/\s\+"version": "\([0-9.]\+\)",/\1/p' package.json`
        export TIMESTAMP=`date +'%Y%m%d%H%M'`
        echo "::set-env name=VERSION_TAG::$PACKAGE_VERSION-$TIMESTAMP"
    - name: Set full image name
      run: |
        export IMAGE_NAME="${{ SECRETS.IMAGE_NAME }}:${{ env.VERSION_TAG }}"
        echo "::set-env name=FULL_IMAGE_NAME::$IMAGE_NAME"
    - name: Build Docker image
      run: docker build -t ${{ env.FULL_IMAGE_NAME }} .
    - name: Push Docker image
      run: docker push ${{ env.FULL_IMAGE_NAME }}
    - name: Perform rolling update
      run: kubectl set image deployments/${{ SECRETS.DEPLOYMENT_NAME }} ${{ SECRETS.DEPLOYMENT_NAME }}=${{ env.FULL_IMAGE_NAME }}
