name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    outputs:
      tag: ${{ steps.meta.outputs.tags }}
    steps:
    - uses: actions/checkout@v4

    - uses: oven-sh/setup-bun@v1

    - run: bun i && bun run build

    - uses: docker/metadata-action@v5
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: latest=false
        tags: type=sha

    - uses: docker/setup-qemu-action@v3
      with:
        platforms: arm64

    - uses: docker/setup-buildx-action@v3
      with:
        platforms: linux/arm64

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v5
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}

  release:
    needs: build
    runs-on: self-hosted
    environment: 'Prod'
    env:
      DEPLOYMENT: ${{ github.event.repository.name }}
    steps:
    - name: Perform rolling update
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${{ needs.build.outputs.tag }}
        kubectl rollout status deployment/${DEPLOYMENT}

    - uses: smartsquaregmbh/delete-old-packages@v0.6.0
      with:
        keep: 2
        type: container
        names: ${{ env.DEPLOYMENT }}
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: ${{ github.event.organization.login }}
