name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v6
    - uses: oven-sh/setup-bun@v2
    - run: bun install
    - run: bunx playwright install chromium --with-deps
    - run: bun run test

  build:
    needs: test
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:
    - uses: actions/checkout@v6
      with:
        fetch-depth: 0

    - uses: oven-sh/setup-bun@v2

    - id: tag
      uses: ietf-tools/semver-action@v1
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        branch: main
        noVersionBumpBehavior: patch
        noNewCommitBehavior: current

    - run: bun i && VITE_APP_VERSION=${{ steps.tag.outputs.nextStrict }} bun run build

    - uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - run: echo "IMAGE_NAME=ghcr.io/${{github.repository}}:${{ steps.tag.outputs.nextStrict }}" >> $GITHUB_ENV

    - uses: docker/build-push-action@v5
      with:
        context: .
        push: true
        tags: ${{ env.IMAGE_NAME }}

    - run: git tag ${{ steps.tag.outputs.nextStrict }} && git push origin ${{ steps.tag.outputs.nextStrict }}

    outputs:
      image_name: ${{ env.IMAGE_NAME }}

  release:
    needs: build
    runs-on: on-prem
    environment: 'Prod'
    env:
      DEPLOYMENT: ${{ github.event.repository.name }}
    steps:
    - name: Perform rolling update
      run: |
        kubectl set image deployment/${DEPLOYMENT} ${DEPLOYMENT}=${{ needs.build.outputs.image_name }} -n default
        kubectl rollout status deployment/${DEPLOYMENT} -n default

    - uses: smartsquaregmbh/delete-old-packages@v0.8.0
      with:
        keep: 2
        type: container
        names: ${{ env.DEPLOYMENT }}
        token: ${{ secrets.GITHUB_TOKEN }}
        organization: ${{ github.event.organization.login }}
