name: Release

on:
  push:
    branches: [ release ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - uses: actions/setup-node@v3
      with:
        node-version: 16
        cache: 'yarn'

    - run: yarn && yarn build

    - uses: docker/metadata-action@v4
      id: meta
      with:
        images: ghcr.io/${{ github.repository }}
        flavor: latest=false
        tags: type=sha

    - uses: docker/setup-qemu-action@v2
      with:
        platforms: arm64

    - uses: docker/setup-buildx-action@v2
      with:
        platforms: linux/arm64

    - uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - uses: docker/build-push-action@v3
      with:
        context: .
        platforms: linux/arm64
        push: true
        tags: ${{ steps.meta.outputs.tags }}
